server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: TAXI-SERVICE
          uri: lb://TAXI-SERVICE
          predicates:
            - Path=/taxirest/**
        - id: PLACE-SERVICE
          uri: lb://PLACE-SERVICE
          predicates:
            - Path=/placerest/**
        - id: PARKING-SERVICE
          uri: lb://PARKING-SERVICE
          predicates:
            - Path=/parkingrest/**
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratingrest/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/userrest/**
        - id: WEB-APP
          uri: lb://WEB-APP
          predicates:
            - Path=/**



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost